/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DictionaryCore: typeof import('./src/components/Dictionary/DictionaryCore.vue')['default']
    DictionarySelector: typeof import('./src/components/Dictionary/DictionarySelector.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    IconBot: typeof import('./src/components/IconBot.vue')['default']
    IconCore: typeof import('./src/components/IconCore.vue')['default']
    IconVoice: typeof import('./src/components/IconVoice.vue')['default']
    IconVoiceVox: typeof import('./src/components/IconVoiceVox.vue')['default']
    IndexBar: typeof import('./src/components/IndexBar/IndexBar.vue')['default']
    LessonSelect: typeof import('./src/components/LessonSelect.vue')['default']
    LinkTo: typeof import('./src/components/LinkTo/LinkTo.vue')['default']
    Reading: typeof import('./src/components/Reading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('./src/components/Row.vue')['default']
    SimpleInput: typeof import('./src/components/SimpleInput.vue')['default']
    SimplePagination: typeof import('./src/components/SimplePagination.vue')['default']
    SimpleSelect: typeof import('./src/components/SimpleSelect.vue')['default']
    TextSelectionMenu: typeof import('./src/components/TextSelectionMenu/TextSelectionMenu.vue')['default']
    VoiceVox: typeof import('./src/components/VoiceVox/VoiceVox.vue')['default']
    WordGraph: typeof import('./src/components/Graph/WordGraph.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
